version: "3.8"

services:
  server:
    build:
      context: .
    container_name: atsast-apply-module-server
    ports:
      - "8080:8080"
    networks:
      - network
    depends_on:
      - database

  database:
    image: mongo:latest
    container_name: atsast-apply-module-database
    ports:
      - "27017:27017"
    networks:
      - network
    volumes:
      - database-volume:/data/db

volumes:
  database-volume:

networks:
  network:
